"""Add connection_id to Attribute

Revision ID: bd5f286450b5
Revises: cc65fe9efb41
Create Date: 2026-03-23 13:13:41.522149

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bd5f286450b5'
down_revision: Union[str, Sequence[str], None] = 'cc65fe9efb41'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('attributes', sa.Column('connection_id', sa.UUID(), nullable=True))
    op.create_foreign_key(None, 'attributes', 'marketplace_connections', ['connection_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'attributes', type_='foreignkey')
    op.drop_column('attributes', 'connection_id')
    # ### end Alembic commands ###
