"""add_category_id_to_attributes

Revision ID: cc65fe9efb41
Revises: 103590999cee
Create Date: 2026-03-23 12:14:31.375887

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cc65fe9efb41'
down_revision: Union[str, Sequence[str], None] = '103590999cee'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('attributes', sa.Column('category_id', sa.UUID(), nullable=True))
    op.create_foreign_key(None, 'attributes', 'categories', ['category_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'attributes', type_='foreignkey')
    op.drop_column('attributes', 'category_id')
    # ### end Alembic commands ###
